server:
  port: 8081

spring:
  application:
    name: devops-training
  config:
    import: vault://
  cloud:
    vault:
      uri: http://vault:8200
      authentication: TOKEN
      token: ${VAULT_TOKEN}   # <= Ici : VAULT_TOKEN injecté comme ENV
      kv:
        enabled: true
        backend: secret
        default-context: application
        profile-separator: "-"
        version: 1
      ssl:
        skip-verify: true

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health, env
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.vault: DEBUG
    org.springframework.cloud.vault: DEBUG
