jenkins:
  systemMessage: "Jenkins configured with JCasC "
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: ${ADMIN_USER}
          password: ${ADMIN_PASSWORD}
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              id: dockerhub-credentials
              username: ${DOCKERHUB_USER}
              password: ${DOCKERHUB_PASSWORD}
          - file:
              id: kubeconfig-gke
              fileName: kubeconfig
              secretBytes: ${KUBECONFIG_BASE64}

unclassified:
  location:
    url: http://jenkins.devops.local

jobs:
  - script: >
      pipelineJob('devops-training-pipeline') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/walidbensmida/devops-training.git')
                }
                branches('*/main')
              }
            }
            scriptPath('acid/jenkins/Jenkinsfile')
          }
        }
      }